// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGi_M8ohF-arYrfBHiNf5s7erq9fmlP74',
    appId: '1:448665477631:web:ec4dfaf031b2a143f587ca',
    messagingSenderId: '448665477631',
    projectId: 'despedidaapp-5524f',
    authDomain: 'despedidaapp-5524f.firebaseapp.com',
    storageBucket: 'despedidaapp-5524f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrvd9A2VB5XhbO3aSIx2eIprhmqL8Iobk',
    appId: '1:448665477631:android:2dfdab31cd2fe79cf587ca',
    messagingSenderId: '448665477631',
    projectId: 'despedidaapp-5524f',
    storageBucket: 'despedidaapp-5524f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDqGrF3qrMdCDi-su8uMDCDARPIj72BT8',
    appId: '1:448665477631:ios:1756cd4b391df1faf587ca',
    messagingSenderId: '448665477631',
    projectId: 'despedidaapp-5524f',
    storageBucket: 'despedidaapp-5524f.firebasestorage.app',
    iosBundleId: 'com.example.despedidaPau',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDqGrF3qrMdCDi-su8uMDCDARPIj72BT8',
    appId: '1:448665477631:ios:1756cd4b391df1faf587ca',
    messagingSenderId: '448665477631',
    projectId: 'despedidaapp-5524f',
    storageBucket: 'despedidaapp-5524f.firebasestorage.app',
    iosBundleId: 'com.example.despedidaPau',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGi_M8ohF-arYrfBHiNf5s7erq9fmlP74',
    appId: '1:448665477631:web:2260e7bd157a3530f587ca',
    messagingSenderId: '448665477631',
    projectId: 'despedidaapp-5524f',
    authDomain: 'despedidaapp-5524f.firebaseapp.com',
    storageBucket: 'despedidaapp-5524f.firebasestorage.app',
  );
}